[package]
name = "asciimation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timer = "0.2.0"
chrono = "0.4.19"
native-dialog = "0.6.1"